### ISSUE TITLE
ability to see parsed data (debug out) without submission

### ISSUE THREAD

**Issue by giovino** [csirtgadgets/csirtg-smrt-py#1]
In CIFv2, when writing a parser for a new feed, we have debug output but that debug output is seen on submission to cifv2 as cif-smrt is tightly coupled to cifv2. 

In this version, cifv2 should be a destination option. So what I guess i'm really asking for is stdout and file based output in addition to cif and csirtg

1. stdout (csv, json, table)
2. file (csv,json,table)
3. cifv2, cifv3
4. csirtg

**Comment by wesyoung** [comment]
https://github.com/csirtgadgets/csirtg-smrt-py/commit/eab43c73b9c3b8741824d2d43fec7c78b348d564
