### ISSUE TITLE
problem: unable to eval a timestamp

### ISSUE THREAD

**Issue by wesyoung** [csirtgadgets/csirtg-smrt-py#142]
eg: use eval + arrow to be able to set lasttime to "this month" or "this week"

(use alexa as an example, update lasttime as the first day of each month?)

**Comment by ShyanFung** [comment]
I did a quick test spin of the improvement/change with the v3.0.0a20 tag and it works great with the now|day case for lasttime.  Verified the record populated in the ES store and appeared in kibana. 

Setting the lasttime field went and populated the firsttime and reportime fields.

**Comment by wesyoung** [comment]
neato. :) ty for the feedback!

did you have to do anything special to get kibana working? would love to get some doc on that:

https://github.com/csirtgadgets/bearded-avenger-deploymentkit/wiki/Where-do-I-start-with-Integrations
