### ISSUE TITLE
problem: cef parser missing --aggregate option

### ISSUE THREAD

**Issue by wesyoung** [csirtgadgets/csirtg-smrt-py#204]
batch indicators_create for a min or two before sending.

**Comment by JustinAzoff** [comment]
Looks like you added this at some point, but it does have an issue, you can't turn it off:

```
justin@dovm1:~$ ./smrt/bin/csirtg-cef  -f ssh.log --provider=justin --client=zmq --aggregate 0
2017-09-10 11:39:01,240 - INFO - root[125] - sending data as: justin
Traceback (most recent call last):
  File "./smrt/bin/csirtg-cef", line 11, in <module>
    load_entry_point('csirtg-smrt==0+unknown', 'console_scripts', 'csirtg-cef')()
  File "/home/justin/smrt/local/lib/python2.7/site-packages/csirtg_smrt/parser/cef.py", line 130, in main
    last_t = round_time(round=int(args.aggregate))
  File "/home/justin/smrt/local/lib/python2.7/site-packages/csirtg_smrt/utils/zarrow.py", line 13, in round_time
    rounding = (seconds+round/2) // round * round
ZeroDivisionError: integer division or modulo by zero
```

I think we'll definitely need this feature, I'll see about fixing it up.  One thing that I do want is some sort of threshold based aggregation like various syslog daemons do.  Say a scanner attempts to login to ssh honeypot once per second for 2 minutes.. I would like the resulting emitted indicators to be

```
 time=1, count=1, indicator=..
 time=2, count=1, indicator=..
 time=3, count=1, indicator=..
 time=4, count=1, indicator=..
 time=5, count=1, indicator=..
 # aggregation kicks in
 time=60, count=55, indicator=..
 time=120, count=60, indicator=...
```

I think the store insertion batching code does almost this exact thing.

This way, we benefit from realtime data sharing for the initial probes, but then start batching the data as it continues to avoid overloading the destination.
