### ISSUE TITLE
problem: RSS parser that extracts lasttime value as date only fails to extract indicator.

### ISSUE THREAD

**Issue by ShyanFung** [csirtgadgets/csirtg-smrt-py#222]
Testing CIF v3.0.0a19

I noticed that the 'configs' and 'configs_md5' feeds in the default zeustracker_abuse_ch.yml rule is not extracting any indicators. Mucking with the configuration indicates some kind of 'smrt' processing issue with the extracted date as lasttime.  I couldn't trace down the the exact cause/break.

**Testing Steps:**
1. Installed cifv3 via BAD-kit.
2. Ran the following cif command to test the configs_md5 feed from zeustracker_abuse_ch.yml:
`csirtg-smrt 
  --token $(more .cif.yml | awk '{ print $2; }') 
  --runtime-path /var/lib/cif 
  -r /etc/cif/rules/default/zeustracker_abuse_ch.yml 
  -f configs_md5 
  --fireball 
  --goback 3 
  --client stdout`
3. Output returned with no extracted indicators from the published RSS feed.
4. I then changed the configs_md5 feed's parsed title values mapping from 'lasttime' to 'description' to see if indicators would be extracted.
https://github.com/csirtgadgets/bearded-avenger/blob/master/rules/default/zeustracker_abuse_ch.yml#L24
https://github.com/csirtgadgets/bearded-avenger/blob/master/rules/default/zeustracker_abuse_ch.yml#L37
5. Ran the command again, and extracted md5 indicator results returned.

**Expected Result:**
1. The extracted indicators from using the RSS parser should allow setting of lasttime as a matched date.  Other parser like pipe used in dataplane.yml can set lasttime.
2. If lasttime is extracted as date date, default to zero hundred time.
3. Possibly just warn of the lasttime error, and proceed with accepting the indicator if it's only an unexpected lasstime value.

**Comment by wesyoung** [comment]
this appears to be a python + requests + openssl issue where the request is getting downgraded to TLSv1 and one of the underlying libs doesn't like that. i mod'd the smrt YML to do "http" instead of HTTPS for the time being. need to dig further into why / how to fix the TLS issues which is trickier when you get into py2 vs py3, etc..

checkout the new YAML file for the work-around.
