### ISSUE TITLE
Optimisation problem

### ISSUE THREAD

**Issue by Nibor62** [csirtgadgets/csirtg-smrt-py#224]
Hi,

Running cifv3 elasticsearch with default configuration and it took nearly 4 hours to parse/update the defaults sources (using --fireball thing).
As I am looking forward to work with domains and urls which contains hundred thousand records, so, is there anyway to speed it up (or could it be linked to running it in virtualbox) ?

Thx

**Comment by wesyoung** [comment]
there are a bunch of performance enhancements to the elasticsearch bits that i just committed to master [for all the same reasons]. in the process of cleaning up and testing myself which should significantly improve your results.. (roughly ~200 upserts/sec, which is still not great, but much faster than what you see now). what you see in default isn't what we run in prod- just enough to show where the cracks and just enough to have others mess with w/o completely falling over.

there's also a "logstash_mode" var that will not upsert (like we do in sqlite) just write out each indicator independently (which has different long term implications). in that mode i've seen upwards of 8k/sec [i'm assuming we can get much higher].

we're load-testing in aws with these new changes (4 nodes, load balanced, etc) and if there are no odd things that crop up we'll cut the next release (a20?). if you end up testing with master; make sure you check out a specific commit in case we make some un-stable changes in the meantime.

at some point you're going to need to split out a smrt specific box, 2-4 cif-routers [load-balanced] boxes and tie those to an elasticsearch backend [also load balanced], which will give you more scalable throughput too.

make sense?

**Comment by Nibor62** [comment]
make sense, thx
I will test logstash_mode before investigating hard updates.

However, I may have gotten into an issue. I'm perf testing V3 with a fake source of 1 million IPs, and after a little while (dunno exactly how many, I noticed it after 4 hours), the update rate fall to ~6.75 entry/s !

**Comment by wesyoung** [comment]
https://github.com/csirtgadgets/bearded-avenger/releases/tag/3.0.0a20
