### ISSUE TITLE
sqlite: Unicode type received for non-unicode bind

### ISSUE THREAD

**Issue by tk-hendrik** [csirtgadgets/csirtg-smrt-py#67]
hmm... something strange for the archiver?

`csirtg-smrt[95809]: /usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/sqltypes.py:185: SAWarning: Unicode type received non-unicode bind param value '170.78.158.65'. (this warning may be suppressed after 10 occurrences)`

**Comment by wesyoung** [comment]
i've seen a few of those, i think they're harmless atm. developing mostly in py3 and then back-porting to python27. haven't had a chance to clean up a lot of the 2.7 unicode warnings associated with sqlite.

if you search for that address, does it show up?

**Comment by tk-hendrik** [comment]
Yes I can search for it but I'm near 100% sure the results come from the ES

**Comment by wesyoung** [comment]
ahhh no this comes from csirtg-smrt using sqlite to "remember" what it's inserted:

https://github.com/csirtgadgets/csirtg-smrt-py/blob/master/csirtg_smrt/archiver.py

before the data is even posted to cif-http/router/store...
