### ISSUE TITLE
problem: feed remote doesn't support regex

### ISSUE THREAD

**Issue by wesyoung** [csirtgadgets/csirtg-smrt-py#88]
for example, if a feed is dropped in a directory with a different timetamp name, there's no way to automatically figure that out.

solution: enable remote to contain regex

**Comment by JustinAzoff** [comment]
regex or glob?  or strftime format?

Sounds like you'd want to be able to say that the feed is

    /feeds/whatever-%Y-%m-%d.csv

**Comment by wesyoung** [comment]
yea. that. was also thinking a flag to purge that file after too...

**Comment by JustinAzoff** [comment]
Shouldn't need to purge the file since the local filename can be constant even if the remote filename changes.

**Comment by wesyoung** [comment]
but i want the option of purging the file :)

**Comment by wesyoung** [comment]
this is gonna require a little fetcher re-factoring .. if only so fetcher doesn't get too crazy wrt caching...
